filetype plugin indent on
set tabstop=4 shiftwidth=4 expandtab
autocmd Filetype sh setlocal expandtab tabstop=2 shiftwidth=2 softtabstop=2
set listchars=nbsp:ʭ,tab:>-,extends:»,precedes:«,trail:• list
